### ISSUE TITLE
File berisi password database seharusnya tidak di-commit ke github

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/sid304-jms#1]
File donjo-app/config/database.php berisi password database yang aktif, dan seharusnya tidak boleh di-commit ke github.

**Comment by eddieridwan** [comment]
Solusi yg diterapkan adalah dengan mengembalikan database.php pada pola versi yang lama, di mana password database yang aktif diambil dari file db_donjo.php, kalau ada. Yg kami lakukan:

- mengubah database.php untuk memakai db_donjo.php kalau ada; kalau tidak memakai password default

- menambahkan file db_donjo.php.contoh yang berisi contoh db_donjo.php dan instruksi meng-copy file tersebut

- menambah file .gitignore dan memasukkan file db_donjo.php supaya file ini tidak di-commit ke github

**Comment by nashihu** [comment]
keren, baru liat github issue yg bahas pakai bahasa indonesia dan serame ini. biasanya inggris mulu. mantuull guys. ijin lewat yak
