### ISSUE TITLE
Perlu menggabungkan versi SID 3.04 lebih baru dari sid.web.id

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/sid304-jms#11]
Kami telah mengunduh SID 3.04 dari sid.web.id pada tanggal 24 Mei 2016. Kode SID yang diunduh tampaknya lebih baru dari yang kami peroleh pada tgl 21 Mei 2016.

Kode SID yang baru diunduh perlu digabung dengan perubahan yang telah kami lakukan.

**Comment by eddieridwan** [comment]
Untuk menangani ini, kami membuat branch baru, _dev_, untuk merekam percobaan penggabungan. Sesudah berhasil baru kemudian branch _dev_ akan di-merge ke _master_. 

Karena begitu banyak file yang berubah dari SID 3.04 20160521 dan SID 3.04 20160524, kami perlu merekam dulu file apa saja yang telah kami ubah pada SID 3.04 20160521. Sesudah itu kami perlu melakukan ulang semua perubahan file2 itu pada SID 3.04 20160524.

Untuk melihat perubahan yang kami lakukan pada SID 3.04 20160521 pada versi 0.1, pakai command terminal:

`$ git diff <sha-tag-v0.1> <sha-commit-pertama>`

**Comment by eddieridwan** [comment]
Kami telah selesai menggabungkan SID 3.04 20160524. Di commit di sid304-jms dengan tag v0.2.

**Comment by bambangsusanto54** [comment]
kenapa pada running teks jalannya terlalu cepat bagaimana cara setting untuk memperlambatnya?

**Comment by RedhoAri** [comment]
Download Sid version 3.04 dimana om?
Jika om berkenan kirim link atau program
Ke email saya. redhoarimeratno12@gmail.com

**Comment by desasoro** [comment]
Download Sid version 3.04 dimana pak.? 
mohon share link atau installernya disini. desasorolambu@gmail.com
terima kasih sudah membantu kami.

**Comment by siayi** [comment]
issues ini telah close.

**Comment by eddieridwan** [comment]
@desasoro : silakan bergabung di https://www.facebook.com/groups/OpenSID. Banyak yang bisa membantu di situ.

Mohon perhatian. Issue bukan tempat bertanya.
