### ISSUE TITLE
Ganti Foto Pada Pengaturan Pengguna Tidak Berhasil

### ISSUE THREAD

**Issue by siayi** [eddieridwan/sid304-jms#20]
Foto tidak berubah setelah menggati foto pada menu pengaturan pengguna (`http://sid.bangundesa.info/index.php/user_setting`) , padahal ketika mengupload file foto dan klik simpan sudah ada pemberitahuan sukses.
![pengaturanuser](https://cloud.githubusercontent.com/assets/1229849/15743574/be2f13f8-28f0-11e6-8d2f-9a9963772612.png)

**Comment by eddieridwan** [comment]
Lihat commit di atas. Diperbaiki, sekaligus menata ulang fungsi update_setting() dan tambah pesan kesalahan.

**Comment by kudalumpink** [comment]
Ternyata banyak juga yg gak berhasil ganti foto github🤣
