### ISSUE TITLE
Import database melalui phpmyadmin di cpanel hosting gagal

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/sid304-jms#3]
Import backup database (sid.sql) melalui phpmyadmin di cpanel hosting gagal. Dengan error:

SQL query: Documentation

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `data_surat` AS select `u`.`id` AS `id`,`u`.`nama` AS `nama`,`x`.`nama` AS `sex`,`u`.`tempatlahir` AS `tempatlahir`,`u`.`tanggallahir` AS `tanggallahir`,(select (date_format(from_days((to_days(now()) - to_days(`tweb_penduduk`.`tanggallahir`))),'%Y') + 0) from `tweb_penduduk` where (`tweb_penduduk`.`id` = `u`.`id`)) AS `umur`,`w`.`nama` AS `status_kawin`,`f`.`nama` AS `warganegara`,`a`.`nama` AS `agama`,`d`.`nama` AS `pendidikan`,`j`.`nama` AS `pekerjaan`,`u`.`nik` AS `nik`,`c`.`rt` AS `rt`,`c`.`rw` AS `rw`,`c`.`dusun` AS `dusun`,`k`.`no_kk` AS `no_kk`,(select `tweb_penduduk`.`nama` from `tweb_penduduk` where (`tweb_penduduk`.`id` = `k`.`nik_kepala`)) AS `kepala_kk` from ((((((((`tweb_penduduk` `u` left join `tweb_penduduk_sex` `x` on((`u`.`sex` = `x`.`id`))) left join `tweb_penduduk_kawin` `w` on((`u`.`status_kawin` = `w`.`id`))) left join `tweb_penduduk_agama` `a` on((`u`.`agama_id` = `a`.`id`))) left jo[...]

MySQL said: Documentation

#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation 

Masalah ini tidak ditemukan sewaktu import di komputer lokal.

**Comment by eddieridwan** [comment]
Edit file sid.sql, hapus DEFINER=root@localhost dan ulangi import.

https://hemantnemade.wordpress.com/2013/07/12/fixphpmyadmin-error-1227-access-denied-you-need-at-least-one-of-the-super-privileges-for-this-operation/

**Comment by widodoari** [comment]
klo versi yang ini untuk import melalui phpmyadmin di cpanel hosting nama "root" di dalam file sql diganti dengan nama user login di cpanelnya

**Comment by zaenalmustopa** [comment]
#1142 - CREATE VIEW command denied to user 'epiz_24926633'@'192.168.0.6' for table 'daftar_anggota_grup

Sudah mencoba di hapus definernya dan root sudah diganti juga tapi tetap error

**Comment by zaenalmustopa** [comment]
#1142 - CREATE VIEW command denied to user 'epiz_24926633'@'192.168.0.6' for table 'daftar_anggota_grup

sudah mencoba definernya di hilangkan, kemudian sudah mencoba di cpanel hosting nama "root" di dalam file sql diganti dengan nama user login di cpanelnya dan error juga 1478-panjang nama user harus kurang dari 16

**Comment by simeud** [comment]
production error sqlstate 42s02 base table or view not found: 1146 table setelah di hosting muncul log error seperti itu
