### ISSUE TITLE
Mengomentari artikel di halaman web membingungkan

### ISSUE THREAD

**Issue by batudaa** [eddieridwan/sid304-jms#30]
Saat mengirimkan komentar untuk artikel, komentar tidak langsung muncul didaftar dan tidak ada informasi kalau komentar perlu di setujui untuk tampil. Dengan begini pengunjung bingung dan beranggapan komentarnya gagal terkirim. Dan mungkin akan mencoba beberapa kali untuk mengirimkan komentar yang sama dan tetap terlihat gagal.

Mestinya ada pesan atau informasi kalau komentar telah berhasil dikirim dan perlu disetujui untuk ditampilkan.

**Comment by eddieridwan** [comment]
Diperbaiki oleh @batudaa.
