### ISSUE TITLE
First Install SID selalu error

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/sid304-jms#34]
Dear Admin 

Kenapa saya selalu error install sid padahal saya udah ikutin panduan install (create db, dan edit file database.php)

error yang terjadi kayak gini

`Unable to Tabel

Filename: D:\xampp\htdocs\desa\donjo-sys\database\DB_driver.php

Line Number: 140`

mohon bantuannya min

**Comment by eddieridwan** [comment]
Apakah data awal atau contoh sudah di-import memakai phpmyadmin? Proses ini sekaligus membuat tabel yang diperlukan. Lihat langkah 6. Import Data Awal di [Panduan install sid304-jms](https://github.com/eddieridwan/sid304-jms/wiki/Panduan-Install-sid304-jms). Apabila mempergunakan release asli SID CRI, nama file .sql akan berbeda.

**Comment by metalab25** [comment]
solved

**Comment by aziztoo** [comment]
Sya jga blm mengerti cara menginstal y,, 

Untuk editdata base php y

**Comment by hienzzo** [comment]
Saya kok muncul pesan " HTTP ERROR 500 " saat buka localhost/opensid

Mohon penjelasannya master... Ane masih nubie.. gagal terus sama pesan tersebut muncul terus T.T

**Comment by ekkykyel** [comment]
Mohon Solusinya

Sebuah Kesalahan Basis Data Telah Terjadi

Error Number: 1146

Table 'unaux_26591104_opensid.penduduk_hidup' doesn't exist

SELECT u.*,(SELECT COUNT(b.id) FROM penduduk_hidup b LEFT JOIN tweb_wil_clusterdesa a ON b.id_cluster = a.id WHERE 1 AND sex = u.id ) AS jumlah,(SELECT COUNT(b.id) FROM penduduk_hidup b LEFT JOIN tweb_wil_clusterdesa a ON b.id_cluster = a.id WHERE sex = 1 AND sex = u.id ) AS laki,(SELECT COUNT(b.id) FROM penduduk_hidup b LEFT JOIN tweb_wil_clusterdesa a ON b.id_cluster = a.id WHERE sex = 2 AND sex = u.id ) AS perempuan FROM tweb_penduduk_sex u

Filename: models/Laporan_penduduk_model.php

Line Number: 548
Harap laporkan masalah ini, agar kami dapat mencarikan solusinya. Untuk sementara Anda dapat kembali ke halaman awal.
