### ISSUE TITLE
SID Terbaru

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/sid304-jms#35]
Dear all 

Mohon info untuk program terbaru SID versi berapa kok kalo saya baca 304 itu di release tahun 2014

**Comment by arzaddin** [comment]
Kalau yang saya tangkap di beberapa diskusi di group fb SID, sepertinya memang begitu. Dan sid ini sudah terus dikembangkan namun tetap mempertahankan angka 304. Tidak tau apa alasan dari pengembang SID.

Untuk sementara 'sub-versi' yang diberikan oleh team JMS yang dijadikan acuan saya :)

**Comment by metalab25** [comment]
Terimakasih informasinya.
