### ISSUE TITLE
Export Doc surat keterangan memerlukan adanya file surat_ket_pengantar_yyyy-mm-dd.rtf

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/sid304-jms#8]
Kalau file SKPyyyymmdd.rtf tidak ada di folder /assets/cetak/, sistem menampilkan error 404 Not Found.

**Comment by siayi** [comment]
hak akses folder kah?

**Comment by eddieridwan** [comment]
Error perlunya file SKPyyyymmdd.rtf  dialami pada versi SID 3.04 yg diperoleh dari https://www.facebook.com/groups/sisteminformasidesa/ tgl 21 Mei. Sedangkan di SID 3.04, sewaktu Export Doc untuk Surat Keterangan, error yg tampil adalah:

`The requested URL /surat/surat_ket_pengantar//surat_ket_pengantar_2016-05-28.rtf was not found on this server.`

Apakah pemakai lain mengalami masalah ini?

**Comment by eddieridwan** [comment]
Kesalahan url dilacak, terjadi di file donjo-app/models/surat_model.php di baris berikut:
`		$mypath="surat\\$url\\";`
`		$path = "".str_replace("\\","/",$mypath)."/";`
`		$file = $path."$url.rtf";`
Sudah kami perbaiki.

**Comment by eddieridwan** [comment]
Kesalahan lain ditemukan di surat_model.php pada baris berikut:
`		$ccyymmdd = date("Y-m-d");`
`		$handle = fopen($path.$url."_".$ccyymmdd.".rtf",'w+');`
`		fwrite($handle,$buffer);`
`		fclose($handle);`
`		$_SESSION['success']=8;`
`		header("location:".base_url().$path.$url."_".$ccyymmdd.".rtf");`

Baris2 ini sepertinya ada dua tujuan: mengurus file sementara penyimpanan surat dan kemudian mengunduh file itu. File yang dibuat tidak didelete, jadi akan terus terkumpul di server. Juga, kalau ada dua surat sejenis, misalnya surat keterangan, yang di -export pada hari yang sama, akan timbul masalah. Apalagi kalau ada lebih dari satu operator yang meng-export surat bersamaan.

Kami ganti cara ini dengan memakai file sementara (tmpfile) yg disediakan php, sehingga namanya selalu unik dan dihapus secara otomatis dari server. Nama file unduhan juga kami perbaiki dengan menempelkan selain tanggal, juga nomor surat.

Dapat dilihat di commit https://github.com/eddieridwan/sid304-jms/commit/40a8253deb6505aca0948dedfbda9a0e93b7e426.
